name: Snapshot

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          install-only: true

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@841d76a188a7c121231a863572e27012805715a2 # v0.1.4

      - name: Run Snapshot
        run: make snapshot

      - name: check binary
        run: |
          ./dist/zeitgeist-amd64-linux version
          ./dist/zeitgeist-remote-amd64-linux version
          ./dist/buoy-amd64-linux help

  attestation:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    needs:
      - snapshot

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 1

      - name: Install tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@841d76a188a7c121231a863572e27012805715a2 # v0.1.4

      - run: |
          tejolote attest github://kubernetes-sigs/zeitgeist/"${GITHUB_RUN_ID}" --output zeitgeist.intoto.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: zeitgeist.intoto.json
          path: ./zeitgeist.intoto.json
