name: Snapshot

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20'
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906 # v4.4.0
        with:
          install-only: true

      - name: Install bom
        uses: puerco/release-actions/setup-bom@6c88cda6495b4415966e61f20798fb96a9081397 # main

      - name: Run Snapshot
        run: make snapshot

      - name: check binary
        run: |
          ./dist/zeitgeist-amd64-linux version
          ./dist/buoy-amd64-linux help
